In [2]:
import pandas as pd
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager
import requests


file_to_load = "Resources/poverty_csv_df.csv"

poverty_csv_df = pd.read_csv(file_to_load)
poverty_csv_df

# poverty_csv_db.drop("District of Columbia", axis = 0, inplace = True)

    Index                 State     Number Lower_Bound_90CI Upper_Bound_90CI
0       1               Alabama    747,478          730,491          764,465
1       2                Alaska     73,033           68,640           77,426
2       3               Arizona    963,007          940,142          985,872
3       4              Arkansas    468,575          456,478          480,672
4       5            California  4,560,419        4,509,811        4,611,027
5       6              Colorado    531,331          516,240          546,422
6       7           Connecticut    343,101          331,999          354,203
7       8              Delaware    106,227          100,509          111,945
8       9  District of Columbia     94,985           88,692          101,278
9      10               Florida  2,681,832        2,641,009        2,722,655
10     11               Georgia  1,397,607        1,370,705        1,424,509
11     12                Hawaii    124,650          118,029          131,271
12     13                 Idaho    193,741          185,524          201,958
13     14              Illinois  1,415,838        1,390,337        1,441,339
14     15               Indiana    773,367          755,582          791,152
15     16                  Iowa    337,156          325,533          348,779
16     17                Kansas    319,931          310,230          329,632
17     18              Kentucky    692,875          677,588          708,162
18     19             Louisiana    847,739          829,070          866,408
19     20                 Maine    141,566          135,542          147,590
20     21              Maryland    537,717          523,164          552,270
21     22         Massachusetts    631,551          615,762          647,340
22     23              Michigan  1,264,445        1,242,287        1,286,603
23     24             Minnesota    491,782          479,460          504,104
24     25           Mississippi    559,764          544,709          574,819
25     26              Missouri    766,238          749,437          783,039
26     27               Montana    130,974          125,732          136,216
27     28              Nebraska    186,402          179,202          193,602
28     29                Nevada    384,900          371,882          397,918
29     30         New Hampshire     98,310           92,374          104,246
30     31            New Jersey    795,676          775,971          815,381
31     32            New Mexico    358,526          348,384          368,668
32     33              New York  2,471,760        2,439,327        2,504,193
33     34        North Carolina  1,383,760        1,358,983        1,408,537
34     35          North Dakota     77,327           72,958           81,696
35     36                  Ohio  1,474,285        1,449,452        1,499,118
36     37              Oklahoma    578,631          567,495          589,767
37     38                Oregon    474,302          461,869          486,735
38     39          Pennsylvania  1,481,193        1,453,602        1,508,784
39     40          Rhode Island    118,095          112,012          124,178
40     41        South Carolina    695,259          677,534          712,984
41     42          South Dakota    101,371           96,713          106,029
42     43             Tennessee    919,850          901,358          938,342
43     44                 Texas  3,870,944        3,820,568        3,921,320
44     45                  Utah    279,435          268,423          290,447
45     46               Vermont     60,624           57,229           64,019
46     47              Virginia    822,944          805,003          840,885
47     48            Washington    731,216          712,292          750,140
48     49         West Virginia    281,175          271,926          290,424
49     50             Wisconsin    591,404          578,030          604,778
50     51               Wyoming     55,776           51,997           59,555

In [2]:
poverty_csv_df.drop(27, axis = 0, inplace = True)
poverty_csv_df

                   State     Number Lower_Bound_90CI Upper_Bound_90CI
0                Alabama    747,478          730,491          764,465
1                 Alaska     73,033           68,640           77,426
2                Arizona    963,007          940,142          985,872
3               Arkansas    468,575          456,478          480,672
4             California  4,560,419        4,509,811        4,611,027
5               Colorado    531,331          516,240          546,422
6            Connecticut    343,101          331,999          354,203
7               Delaware    106,227          100,509          111,945
8   District of Columbia     94,985           88,692          101,278
9                Florida  2,681,832        2,641,009        2,722,655
10               Georgia  1,397,607        1,370,705        1,424,509
11                Hawaii    124,650          118,029          131,271
12                 Idaho    193,741          185,524          201,958
13              Illinois  1,415,838        1,390,337        1,441,339
14               Indiana    773,367          755,582          791,152
15                  Iowa    337,156          325,533          348,779
16                Kansas    319,931          310,230          329,632
17              Kentucky    692,875          677,588          708,162
18             Louisiana    847,739          829,070          866,408
19                 Maine    141,566          135,542          147,590
20              Maryland    537,717          523,164          552,270
21         Massachusetts    631,551          615,762          647,340
22              Michigan  1,264,445        1,242,287        1,286,603
23             Minnesota    491,782          479,460          504,104
24           Mississippi    559,764          544,709          574,819
25              Missouri    766,238          749,437          783,039
26               Montana    130,974          125,732          136,216
28              Nebraska    186,402          179,202          193,602
29                Nevada    384,900          371,882          397,918
30         New Hampshire     98,310           92,374          104,246
31            New Jersey    795,676          775,971          815,381
32            New Mexico    358,526          348,384          368,668
33              New York  2,471,760        2,439,327        2,504,193
34        North Carolina  1,383,760        1,358,983        1,408,537
35          North Dakota     77,327           72,958           81,696
36                  Ohio  1,474,285        1,449,452        1,499,118
37              Oklahoma    578,631          567,495          589,767
38                Oregon    474,302          461,869          486,735
39          Pennsylvania  1,481,193        1,453,602        1,508,784
40          Rhode Island    118,095          112,012          124,178
41        South Carolina    695,259          677,534          712,984
42          South Dakota    101,371           96,713          106,029
43             Tennessee    919,850          901,358          938,342
44                 Texas  3,870,944        3,820,568        3,921,320
45                  Utah    279,435          268,423          290,447
46               Vermont     60,624           57,229           64,019
47              Virginia    822,944          805,003          840,885
48            Washington    731,216          712,292          750,140
49         West Virginia    281,175          271,926          290,424
50             Wisconsin    591,404          578,030          604,778
51               Wyoming     55,776           51,997           59,555

In [3]:
poverty_csv_df.to_csv(r'poverty_csv_df.csv')