In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
file_to_load = "Resources/2019USPopulation.csv"
population_db = pd.read_csv(file_to_load)
population_db

                   State    2019_Pop
0                Alabama   4,903,185
1                 Alaska     731,545
2                Arizona   7,278,717
3               Arkansas   3,017,804
4             California  39,512,223
5               Colorado   5,758,736
6            Connecticut   3,565,287
7               Delaware     973,764
8   District of Columbia     705,749
9                Florida  21,477,737
10               Georgia  10,617,423
11                Hawaii   1,415,872
12                 Idaho   1,787,065
13              Illinois  12,671,821
14               Indiana   6,732,219
15                  Iowa   3,155,070
16                Kansas   2,913,314
17              Kentucky   4,467,673
18             Louisiana   4,648,794
19                 Maine   1,344,212
20              Maryland   6,045,680
21         Massachusetts   6,892,503
22              Michigan   9,986,857
23             Minnesota   5,639,632
24           Mississippi   2,976,149
25              Missouri   6,137,428
26               Montana   1,068,778
27              Nebraska   1,934,408
28                Nevada   3,080,156
29         New Hampshire   1,359,711
30            New Jersey   8,882,190
31            New Mexico   2,096,829
32              New York  19,453,561
33        North Carolina  10,488,084
34          North Dakota     762,062
35                  Ohio  11,689,100
36              Oklahoma   3,956,971
37                Oregon   4,217,737
38          Pennsylvania  12,801,989
39          Rhode Island   1,059,361
40        South Carolina   5,148,714
41          South Dakota     884,659
42             Tennessee   6,829,174
43                 Texas  28,995,881
44                  Utah   3,205,958
45               Vermont     623,989
46              Virginia   8,535,519
47            Washington   7,614,893
48         West Virginia   1,792,147
49             Wisconsin   5,822,434
50               Wyoming     578,759
51           Puerto Rico   3,193,694

In [3]:
database_path = "Resources/population.sqlite"
engine = create_engine(f"sqlite:///{database_path}")

In [4]:
population_db.to_sql('population', con = engine)

In [5]:
print(engine.execute("SELECT * FROM population").fetchall())

[(0, 'Alabama', '4,903,185'), (1, 'Alaska', '731,545'), (2, 'Arizona', '7,278,717'), (3, 'Arkansas', '3,017,804'), (4, 'California', '39,512,223'), (5, 'Colorado', '5,758,736'), (6, 'Connecticut', '3,565,287'), (7, 'Delaware', '973,764'), (8, 'District of Columbia', '705,749'), (9, 'Florida', '21,477,737'), (10, 'Georgia', '10,617,423'), (11, 'Hawaii', '1,415,872'), (12, 'Idaho', '1,787,065'), (13, 'Illinois', '12,671,821'), (14, 'Indiana', '6,732,219'), (15, 'Iowa', '3,155,070'), (16, 'Kansas', '2,913,314'), (17, 'Kentucky', '4,467,673'), (18, 'Louisiana', '4,648,794'), (19, 'Maine', '1,344,212'), (20, 'Maryland', '6,045,680'), (21, 'Massachusetts', '6,892,503'), (22, 'Michigan', '9,986,857'), (23, 'Minnesota', '5,639,632'), (24, 'Mississippi', '2,976,149'), (25, 'Missouri', '6,137,428'), (26, 'Montana', '1,068,778'), (27, 'Nebraska', '1,934,408'), (28, 'Nevada', '3,080,156'), (29, 'New Hampshire', '1,359,711'), (30, 'New Jersey', '8,882,190'), (31, 'New Mexico', '2,096,829'), (32, 'New York', '19,453,561'), (33, 'North Carolina', '10,488,084'), (34, 'North Dakota', '762,062'), (35, 'Ohio', '11,689,100'), (36, 'Oklahoma', '3,956,971'), (37, 'Oregon', '4,217,737'), (38, 'Pennsylvania', '12,801,989'), (39, 'Rhode Island', '1,059,361'), (40, 'South Carolina', '5,148,714'), (41, 'South Dakota', '884,659'), (42, 'Tennessee', '6,829,174'), (43, 'Texas', '28,995,881'), (44, 'Utah', '3,205,958'), (45, 'Vermont', '623,989'), (46, 'Virginia', '8,535,519'), (47, 'Washington', '7,614,893'), (48, 'West Virginia', '1,792,147'), (49, 'Wisconsin', '5,822,434'), (50, 'Wyoming', '578,759'), (51, 'Puerto Rico', '3,193,694')]